#!/usr/bin/env python3

import sys
import cgi
import codecs
from pygments.lexers import get_lexer_for_filename
from pygments import highlight
from pygments.formatters import HtmlFormatter

sys.stdin = codecs.getreader("utf-8")(sys.stdin.detach())
doc = sys.stdin.read()
try:
	lexer = get_lexer_for_filename(sys.argv[1])
	formatter = HtmlFormatter(style='pastie')
	sys.stdout.write("<style>")
	sys.stdout.write(formatter.get_style_defs('.highlight'))
	sys.stdout.write("</style>")

	highlight(doc, lexer, formatter, sys.stdout)
except:
	sys.stdout.write(str(cgi.escape(doc).encode("ascii", "xmlcharrefreplace"), "ascii"))
